// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskSystem_Back.Data;

#nullable disable

namespace TaskSystem_Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619140829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskSystem_Back.Models.ClientCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientCompanies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector tecnología y dispositivos móviles.",
                            Name = "Honor"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector deportivo y moda.",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empresa cliente del sector telecomunicaciones.",
                            Name = "Tigo"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medios tradicionales: TV, radio, prensa y vía pública.",
                            Name = "ATL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estrategia y ejecución de campañas en medios digitales.",
                            Name = "Digital"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diseño gráfico y producción visual de piezas.",
                            Name = "Diseño"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conceptualización creativa de campañas y contenidos.",
                            Name = "Creatividad"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Generación de contenido para redes y plataformas digitales.",
                            Name = "Content"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gestión y seguimiento directo de las cuentas de clientes.",
                            Name = "Ejecutivo de cuenta"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dirección y gestión general de la empresa.",
                            Name = "Gerencia"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.DepartmentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("DepartmentUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222207"),
                            Email = "vernica.paz@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444401")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Email = "vanet.garcia@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444402")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Email = "anto.pomacusi@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444403")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Email = "anto.pomacusi@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444403")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Email = "yoss.quiroga@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444407")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Email = "belen.rodriguez@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444408")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222206"),
                            Email = "gabriel.aguilar@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444409")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Email = "ariane.alvarez@gmail.com",
                            Password = "$2b$11$nimYdExq5VFLkLlkcI2/aeCSrdXHIIZ8ytITFH13EMfcIM8LWB4Sy",
                            UserId = new Guid("44444444-4444-4444-4444-444444444410")
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444404"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Campaña integral de branding y marketing para el lanzamiento del nuevo modelo.",
                            EndDate = new DateOnly(2026, 8, 31),
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555501"),
                            StartDate = new DateOnly(2026, 6, 1),
                            Title = "Campaña de lanzamiento Honor X10"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444405"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Producción audiovisual de spot para campaña de la línea de running.",
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555503"),
                            StartDate = new DateOnly(2026, 7, 1),
                            Title = "Spot publicitario Adidas Running"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666603"),
                            ClientUserId = new Guid("44444444-4444-4444-4444-444444444406"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Planificación y compra de espacios publicitarios para el tercer trimestre.",
                            EndDate = new DateOnly(2026, 9, 30),
                            ProjectTypeId = new Guid("55555555-5555-5555-5555-555555555504"),
                            StartDate = new DateOnly(2026, 7, 15),
                            Title = "Plan de medios Tigo Q3"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.ProjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Proyectos de construcción e identidad de marca.",
                            Name = "Branding"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estrategias y campañas de marketing en general.",
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Producción de video, fotografía y contenido audiovisual.",
                            Name = "Producción Audiovisual"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Planificación y compra de espacios publicitarios.",
                            Name = "Medios Publicitarios"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Usuario externo que representa a una empresa cliente.",
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Responsable de la gestión general y toma de decisiones.",
                            Name = "Gerente"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lidera un área o departamento de la empresa.",
                            Name = "Director"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal operativo con mayor nivel de experiencia.",
                            Name = "Operativo 1"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personal operativo de nivel inicial.",
                            Name = "Operativo 2"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estudiante en formación práctica dentro de la empresa.",
                            Name = "Pasante"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.SubProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("SubProjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Detail = "Creación de banners, posts y material gráfico para la campaña.",
                            EndDate = new DateOnly(2026, 6, 20),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666601"),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "En curso",
                            Title = "Diseño de piezas gráficas - Lanzamiento Honor X10"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777702"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222204"),
                            Detail = "Desarrollo creativo del concepto y guion para el spot audiovisual.",
                            EndDate = new DateOnly(2026, 7, 10),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666602"),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            Title = "Guion y storyboard - Spot Adidas Running"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777703"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Detail = "Negociación y reserva de espacios publicitarios para el trimestre.",
                            EndDate = new DateOnly(2026, 8, 1),
                            ProjectId = new Guid("66666666-6666-6666-6666-666666666603"),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            Title = "Compra de espacios en medios - Tigo Q3"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.SubTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("SubTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999901"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Definir colores acorde a la identidad de marca de Honor.",
                            EndDate = new DateOnly(2026, 6, 2),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "Completado",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Title = "Seleccionar paleta de colores"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999902"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Buscar referencias de spots similares para inspiración del guion.",
                            EndDate = new DateOnly(2026, 7, 2),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888802"),
                            Title = "Investigar referencias narrativas"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999903"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Armar lista de proveedores y solicitar datos de contacto.",
                            EndDate = new DateOnly(2026, 7, 16),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            TaskItemId = new Guid("88888888-8888-8888-8888-888888888803"),
                            Title = "Contactar proveedores de vallas"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("SubProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888801"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Banner para Instagram y Facebook con las dimensiones requeridas por campaña.",
                            EndDate = new DateOnly(2026, 6, 5),
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "En curso",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Title = "Diseñar banner principal para redes"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888802"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Primera versión del guion narrativo para revisión del cliente.",
                            EndDate = new DateOnly(2026, 7, 4),
                            StartDate = new DateOnly(2026, 7, 1),
                            Status = "Pendiente",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777702"),
                            Title = "Redactar guion del spot"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888803"),
                            AssignedUserId = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Detail = "Solicitar cotizaciones a proveedores de espacios publicitarios.",
                            EndDate = new DateOnly(2026, 7, 20),
                            StartDate = new DateOnly(2026, 7, 15),
                            Status = "Pendiente",
                            SubProjectId = new Guid("77777777-7777-7777-7777-777777777703"),
                            Title = "Cotizar espacios en vía pública"
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientCompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Vernica",
                            LastName = "Paz",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Vanet",
                            LastName = "Garcia",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Anto",
                            LastName = "Pomacusi",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111103")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Carlos",
                            LastName = "Apala",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Harold",
                            LastName = "Apaza",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            ClientCompanyId = new Guid("33333333-3333-3333-3333-333333333303"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Miguel",
                            LastName = "Calvimontes",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Yoss",
                            LastName = "Quiroga",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Belen",
                            LastName = "Rodriguez",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111105")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Gabriel",
                            LastName = "Aguilar",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Ariane",
                            LastName = "Alvarez",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111104")
                        });
                });

            modelBuilder.Entity("TaskSystem_Back.Models.DepartmentUser", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSystem_Back.Models.User", "User")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.Project", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.User", "ClientUser")
                        .WithMany()
                        .HasForeignKey("ClientUserId");

                    b.HasOne("TaskSystem_Back.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientUser");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.SubProject", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("TaskSystem_Back.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSystem_Back.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.SubTask", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("TaskSystem_Back.Models.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.TaskItem", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("TaskSystem_Back.Models.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.User", b =>
                {
                    b.HasOne("TaskSystem_Back.Models.ClientCompany", "ClientCompany")
                        .WithMany()
                        .HasForeignKey("ClientCompanyId");

                    b.HasOne("TaskSystem_Back.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskSystem_Back.Models.User", b =>
                {
                    b.Navigation("DepartmentUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
